DROP TABLE BOOK ;
CREATE TABLE BOOK
(
 BOOK_ID       	BIGINT     UNSIGNED NOT NULL,  
 TITLE     	VARCHAR(255)         , 
 COST      	FLOAT(10,2)          , 
 PUBLISH_TIME	DATE,			
 BLOB_CONTENT   LONGBLOB,
 TEXT_CONTENT   LONGTEXT,
 PRIMARY KEY(BOOK_ID)
) ;


DROP TABLE BOOK_EDITOR ;
CREATE TABLE BOOK_EDITOR( 
  BOOK_ID BIGINT    UNSIGNED NOT NULL,	
  EDITOR_ID BIGINT  UNSIGNED NOT NULL,	
  PRIMARY KEY(BOOK_ID, EDITOR_ID)
) ;


DROP TABLE EDITOR ;
CREATE TABLE EDITOR (	  
  EDITOR_ID     BIGINT UNSIGNED NOT NULL   ,
  NAME    	VARCHAR(80)     NOT NULL   ,
  SEX		SET('M','F') ,		    	
  PRIMARY KEY(EDITOR_ID)
);



